version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=接口自动化测试平台
      - DEBUG=true
      - DATABASE_URL=mysql://root:password@mysql:3306/test_platform_dev
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=docker-secret-key-change-in-production
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logs:/app/logs

  celery:
    build: .
    command: python start_celery.py
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/test_platform_dev
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=docker-secret-key-change-in-production
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_platform_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data: